server.port=8080

# Spring Data JPA
spring.datasource.url=jdbc:postgresql://dpg-d671lpg6fj8s7381iheg-a:5432/platzi_play_db
spring.datasource.username=juan
spring.datasource.password=MDmOKaQIU0vyijHoMUMp8hRBIPPC5iMU

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

#LangChain4j
langchain4j.open-ai.chat-model.api-key=demo

